export const defaultExpertiseProgress = {
  level: 0,

  weapons: {
    Rifles: { current: 1, total: 36 },
    "Assault Rifles": { current: 1, total: 55 },
    "Marksman Rifles": { current: 2, total: 32 },
    Shotguns: { current: 1, total: 32 },
    SMGs: { current: 0, total: 44 },
    LMGs: { current: 1, total: 38 },
    Pistols: { current: 1, total: 31 },
    Specialization: { current: 0, total: 6 },
  },

  namedGear: {
    Masks: { current: 1, total: 12 },
    "Body Armor": { current: 0, total: 28 },
    Backpacks: { current: 0, total: 27 },
    Gloves: { current: 0, total: 11 },
    Holsters: { current: 0, total: 13 },
    Kneepads: { current: 0, total: 12 },
  },

  skills: {
    "Sticky Bomb": { current: 0, total: 3 },
    Trap: { current: 0, total: 3 },
    Decoy: { current: 0, total: 1 },
    Pulse: { current: 0, total: 5 },
    Turret: { current: 1, total: 4 },
    Hive: { current: 1, total: 5 },
    "Chem Launcher": { current: 0, total: 4 },
    Firefly: { current: 0, total: 3 },
    "Seeker Mine": { current: 0, total: 4 },
    Drone: { current: 2, total: 5 },
    "Ballistic Shield": { current: 1, total: 4 },
    "Smart Cover": { current: 0, total: 2 },
  },

  brands: {
    Electrique: 3,
    "Habsburg Guard": 7,
    "Brazos de Arcabuz": 4,
    "Uzina Getica": 6,
    "Empress International": 4,
    "Belstone Armory": 4,
    "Walker, Harris & Co.": 5,
    "Murakami Industries": 0,
    "Hana-U Corporation": 4,
    "Sokolov Concern": 4,
    "Grupo Sombra S.A.": 5,
    "Česká Výroba s.r.o.": 5,
    "Edelweiss GP-2": 6,
    "Douglas & Harding": 5,
    "Royal Works": 5,
    "Badger Tuff": 7,
    "Unit Alloys": 0,
    "Providence Defense": 7,
    "Urban Lookout": 5,
    "Overlord Armaments": 6,
    "Petrov Defense Group": 5,
    "Shiny Monkey Gear": 6,
    "Yaahl Gear": 0,
    "Legatus S.p.A.": 5,
    "Richter & Kaiser GmbH": 7,
    "Svadovka Sp. z o.o.": 5,
    "Gila Guard": 7,
    "Palisade Steelworks": 4,
    "Golan Gear Ltd": 7,
    Lengmo: 5,
    "Wyvern Wear": 6,
    "Fenris Group AB": 8,
    "Airaldi Holdings": 0,
    "Petrov Defense Group": 5,
    "Alps Summit Armament": 7,
    "5.11 Tactical": 9,
  },

  gearSets: {
    "Core Strength": 0,
    "Concentrated Companionship": 0,
    "Tipping Scales": 3,
    "Measured Asset": 1,
    Refactor: 3,
    Virtuoso: 3,
    "Breaking Point": 0,
    Aegis: 3,
    Cavalier: 0,
    "Ortiz: Exuro": 0,
    Hotshot: 1,
    "Umbra Initiative": 0,
    Heartbreaker: 0,
    Rigger: 7,
    "Hunter's Fury": 0,
    "Eclipse Protocol": 1,
    "Striker's Battlegear": 0,
    "Future Initiative": 0,
    "Foundry Bulwark": 2,
    "System Corruption": 0,
    "Ortiz: Reficere": 0,
    "Aces & Eights": 1,
    "Tip of the Spear": 3,
    "Negotiator's Dilemma": 2,
    "Hard Wired": 1,
    "True Patriot": 3,
    "Ongoing Directive": 2,
  },
}